import type { CardValue } from "@/components/figure/card/table";

export const pl: CardValue[] = [
  {
    value: 1224,
    diff: 120,
    strong: true,
    key: "revenue",
    sortable: true,
  },
  {
    value: 1124,
    diff: 0,
    strong: true,
    key: "expense",
    sortable: true,
  },
  {
    value: 100,
    diff: -20,
    emphasized: true,
    strong: true,
    key: "op_profit",
    sortable: true,
  },
  {
    value: 24,
    diff: -10,
    inset: true,
    key: "no_rev",
    sortable: true,
  },
  {
    value: 14,
    diff: 4,
    inset: true,
    key: "no_exp",
    sortable: true,
  },
  {
    value: 110,
    diff: -24,
    emphasized: true,
    strong: true,
    key: "ordinary_profit",
    sortable: true,
  },
  { value: 0, diff: 0, inset: true, key: "sp_rev", sortable: true },
  { value: 0, diff: 0, inset: true, key: "sp_exp", sortable: true },
  {
    value: 110,
    diff: -24,
    emphasized: true,
    strong: true,
    key: "profit_before_tax",
    sortable: true,
  },
  {
    value: 110,
    diff: -24,
    inset: true,
    key: "tax",
    sortable: true,
  },
  {
    value: -110,
    diff: -24,
    emphasized: true,
    strong: true,
    redIfMinus: true,
    key: "profit",
    sortable: true,
  },
  {
    value: 110,
    diff: -24,
    key: "related_revenue",
    sortable: true,
  },
];
