export const pl = [
  {
    value: 1224,
    diff: 120,
    strong: true,
    key: "revenue",
    sortable: true,
  },
  {
    value: 1124,
    diff: 0,
    strong: true,
    key: "expenses",
    sortable: true,
  },
  {
    value: 100,
    diff: -20,
    emphasized: true,
    strong: true,
    key: "operating_profit",
    sortable: true,
  },
  {
    value: 24,
    diff: -10,
    inset: true,
    key: "non_operating_income",
    sortable: true,
  },
  {
    value: 14,
    diff: 4,
    inset: true,
    key: "non_operating_expenses",
    sortable: true,
  },
  {
    value: 110,
    diff: -24,
    emphasized: true,
    strong: true,
    key: "ordinary_profit",
    sortable: true,
  },
  {
    value: 0,
    diff: 0,
    inset: true,
    key: "extraordinary_income",
    sortable: true,
  },
  { value: 0, diff: 0, inset: true, key: "extraordinary_loss", sortable: true },
  {
    value: 110,
    diff: -24,
    emphasized: true,
    strong: true,
    key: "profit_before_tax",
    sortable: true,
  },
  {
    value: 110,
    diff: -24,
    inset: true,
    key: "tax",
    sortable: true,
  },
  {
    value: -110,
    diff: -24,
    emphasized: true,
    strong: true,
    redIfMinus: true,
    key: "net_profit",
    sortable: true,
  },
  {
    value: 110,
    diff: -24,
    key: "related_companies_revenue",
    sortable: true,
  },
];
